### PR TITLE
Wrote starter for securing the mail form a little bit

### PR DESCRIPTION
**Pull request by worr**
This is broken. I can arbitrarily email anyone anywhere from CSH.
# This is a bad thing

Here is a starter. Something better than `die` should probably be used for error handling, but this should get you started.

I hate PHP.

### CODE REVIEW

**Comment by bencentra** [comment]
```
// Make sure the recipient is an accepted address
$EMAIL_ADDRESSES = array(
  "chairman@csh.rit.edu",
  "eval@csh.rit.edu",
  "history@csh.rit.edu",
  "scholarship@csh.rit.edu",
  "webmaster@csh.rit.edu"
);

// Sanitize the name
$name = preg_replace("/[^a-zA-Z0-9 .,-]/", "", $_POST['f1']);
// Get the message body
$message = $_POST['f3'];

// Make sure the email is valid
$email = filter_var($_POST['f2'], FILTER_VALIDATE_EMAIL);
if (!$email) {
    header("Location: failure.php");
    exit;
}

// Make sure the recipient is an expected address
$recipient = $_POST['sendtoemail'];  
if (!in_array($recipient, $EMAIL_ADDRESSES, TRUE)) {
    header("Location: failure.php");
    exit;
}

// Form the email
$formcontent="From: $name \nEmail: $email \nMessage: $message";
$subject = "A Message from the CSH Public Website";
$mailheader = "From: $email \r\n";

// Send the email
$success = mail($recipient, $subject, $formcontent, $mailheader);
if (!$success) {
    header("Location: failure.php");
    exit;
}

// Redirect to success page
header("Location: thankyou.php");
```

**Comment by worr** [comment]
Oh honey no.

http://php.net/manual/en/function.filter-var.php

You want to sanitize it with the SANITIZE_EMAIL bullshit.

Never, ever write sanitization code yourself. You'll probably lose data, and not write check for all possible injections. 99% of the time it's been done for you.

**Comment by worr** [comment]
My boo here with my last comment.

FILTER_SANITIZE_EMAIL is not what you want for the other fields. The documentation I read had alluded to it filtering headers.

For what you want, make sure you remove crlf from any of the user submitted fields, that way no one can spoof in any more headers.

Also us FILTER_VALIDATE_EMAIL like you are to verify that the email is valid.

Even better, you can always ask for it twice, and assume it's valid, since most people do email validation wrong. rfc822 is fucking extreme (email addresses can have comments).

**Comment by clockfort** [comment]
Christ, I just accidentally re-discovered this security vuln while taking a five second look at the source code. Fucking fix it, right now anyone can use the god damn main webserver as an open spam relay.

**Comment by clockfort** [comment]
On a related note, if this is not fixed within the week, I will write a script to use the form to email Gorbachev, Centra, and Worr every minute until they finish this patch and push it to production.

**Comment by worr** [comment]
For the love of all that is holy please merge this in and push it today.

**Pull request merged**
